


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."exec_sql"("sql" "text") RETURNS SETOF "jsonb"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN QUERY EXECUTE format('SELECT to_jsonb(t) FROM (%s) t', sql);
END;
$$;


ALTER FUNCTION "public"."exec_sql"("sql" "text") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."alumno_estados" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email_enviado" "date",
    "match_fp" "date",
    "fp_enprogreso" "date",
    "fp_finalizada" "date",
    "alumno" character varying NOT NULL,
    "form_completo" "date",
    "documentacion_completa" "date",
    "evaluacion_enviada" "date",
    "evaluacion_completa" "date",
    "fp_asignada" "date",
    "fp_cancelada" "date"
);


ALTER TABLE "public"."alumno_estados" OWNER TO "postgres";


ALTER TABLE "public"."alumno_estados" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."alumno_estados_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."alumnos" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "NIA" character varying,
    "nombre" character varying,
    "apellido" character varying,
    "telefono" character varying,
    "provincia" character varying,
    "localidad" character varying,
    "codigo_postal" character varying,
    "direccion" character varying,
    "email_alumno" character varying,
    "sexo" character varying,
    "preferencias_fp" "jsonb",
    "vehiculo" "text",
    "ciclo_formativo" "jsonb",
    "estado" character varying,
    "motivo" character varying,
    "dni" "text" NOT NULL,
    "requisitos" character varying,
    "tipoPractica" "text",
    "gestor" "text",
    "tutor_centro" "text",
    "horas_totales" integer,
    "comentarios_centro" "text",
    "observaciones_seguimiento" "text",
    "anio" "text",
    "nuss" "text",
    "curso" "text"
);


ALTER TABLE "public"."alumnos" OWNER TO "postgres";


ALTER TABLE "public"."alumnos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."alumnos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."contacto_alumnos" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email_alumno" character varying NOT NULL,
    "email_enviado" "date"
);


ALTER TABLE "public"."contacto_alumnos" OWNER TO "postgres";


ALTER TABLE "public"."contacto_alumnos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."contacto_alumnos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."contacto_empresas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email_empresa" character varying NOT NULL,
    "email_enviado" "date"
);


ALTER TABLE "public"."contacto_empresas" OWNER TO "postgres";


ALTER TABLE "public"."contacto_empresas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."contacto_empresas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."empresa_estados" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email_enviado" "date",
    "form_completo" "date",
    "contrato_firmado" "date",
    "fp_asignada" "date",
    "fp_enprogreso" "date",
    "fp_finalizada" "date",
    "empresa" character varying NOT NULL,
    "documentacion_completa" "date",
    "match_fp" "date",
    "evaluacion_enviada" "date",
    "evaluacion_completa" "date"
);


ALTER TABLE "public"."empresa_estados" OWNER TO "postgres";


ALTER TABLE "public"."empresa_estados" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."empresa_estados_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."oferta_fp" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "empresa" character varying NOT NULL,
    "ciclos_formativos" "jsonb",
    "puestos" "jsonb",
    "requisitos" character varying,
    "contrato" character varying,
    "vehiculo" character varying,
    "estado" character varying,
    "motivo" character varying,
    "direccion_empresa" character varying,
    "localidad_empresa" character varying,
    "cp_empresa" character varying,
    "nombre_rellena_form" character varying,
    "cupo_alumnos" real,
    "tutor" bigint,
    "tipo" "text",
    "seguimiento_gestores" "jsonb",
    "tutores_por_puesto" "jsonb"
);


ALTER TABLE "public"."oferta_fp" OWNER TO "postgres";


ALTER TABLE "public"."oferta_fp" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."empresa_practica_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."empresas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "CIF" character varying NOT NULL,
    "nombre" "text",
    "direccion" "text",
    "provincia" "text",
    "localidad" "text",
    "codigo_postal" character varying,
    "telefono" "text",
    "fax" "text",
    "sectorEmpresa" "text",
    "email_empresa" "text",
    "responsable_legal" "text",
    "nif_responsable_legal" "text",
    "horario" "text",
    "pagina_web" "text",
    "nombre_rellena" "text"
);


ALTER TABLE "public"."empresas" OWNER TO "postgres";


ALTER TABLE "public"."empresas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."empresas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."error_logs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "log" "text",
    "pagina" "text"
);


ALTER TABLE "public"."error_logs" OWNER TO "postgres";


ALTER TABLE "public"."error_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."error_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."feedback_forms" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "practica_id" bigint,
    "tipo_form" "text",
    "token" "text",
    "estado" "text",
    "fecha_envio" "date",
    "fecha_respuesta" "date",
    "email_destino" "text",
    "fecha_real_envio" "text"
);


ALTER TABLE "public"."feedback_forms" OWNER TO "postgres";


ALTER TABLE "public"."feedback_forms" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."feedback_forms_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."feedback_respuestas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "feedback_form_id" bigint NOT NULL,
    "practica_id" bigint NOT NULL,
    "respuestas_json" "jsonb"
);


ALTER TABLE "public"."feedback_respuestas" OWNER TO "postgres";


ALTER TABLE "public"."feedback_respuestas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."feedback_respuestas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."form_answers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "form" bigint,
    "field_id" bigint,
    "empresa" character varying,
    "value" "text",
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."form_answers" OWNER TO "postgres";


ALTER TABLE "public"."form_answers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."form_answers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."form_fields" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "form" bigint,
    "label" "text",
    "type" "text",
    "options" "jsonb",
    "required" boolean,
    "order_index" bigint,
    "category" "text",
    "columnName" "text"
);


ALTER TABLE "public"."form_fields" OWNER TO "postgres";


ALTER TABLE "public"."form_fields" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."form_fields_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."forms" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" character varying,
    "tipo" character varying,
    "descripcion" "text"
);


ALTER TABLE "public"."forms" OWNER TO "postgres";


ALTER TABLE "public"."forms" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."forms_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."gestores" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" "text",
    "activo" boolean,
    "email" "text",
    "ciclo" "text",
    "password" "text"
);


ALTER TABLE "public"."gestores" OWNER TO "postgres";


ALTER TABLE "public"."gestores" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."gestores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."localidades" (
    "id" bigint NOT NULL,
    "nombre" "text" NOT NULL,
    "provincia" "text" NOT NULL
);


ALTER TABLE "public"."localidades" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."practica_estados" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "practicaId" bigint NOT NULL,
    "documentacion_pedida" "date",
    "documentacion_firmada" "date",
    "en_progreso" "date",
    "cancelada" "date",
    "finalizada" "date"
);


ALTER TABLE "public"."practica_estados" OWNER TO "postgres";


ALTER TABLE "public"."practica_estados" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."practica_estados_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."practicas_canceladas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "alumno" "text",
    "empresa" "text",
    "ciclo" "text",
    "motivo" "text",
    "anio" "text",
    "curso" "text",
    "tutor_centro" "text",
    "tutor" "text",
    "area" "text",
    "gestor" "text",
    "feedback" "jsonb",
    "fecha_inicio" "text",
    "feedbackEmpresa" "text"
);


ALTER TABLE "public"."practicas_canceladas" OWNER TO "postgres";


ALTER TABLE "public"."practicas_canceladas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."practicas_canceladas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."practicas_fp" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "empresa" character varying,
    "oferta" bigint,
    "alumno" "text",
    "ciclo_formativo" character varying,
    "area" character varying,
    "proyecto" character varying,
    "fecha_inicio" "date",
    "tutor" "text",
    "feedback_tutor" "jsonb",
    "anexos_creados" boolean,
    "anexos_enviados" boolean,
    "anexos_firmados" boolean,
    "doc_sao_entregada" boolean,
    "status" "text",
    "tutor_centro" "text",
    "gestor" "text",
    "motivo" "text",
    "feedback_tutor_centro" "jsonb",
    "direccion" "text",
    "localidad" "text",
    "anio" "text",
    "curso" "text"
);


ALTER TABLE "public"."practicas_fp" OWNER TO "postgres";


ALTER TABLE "public"."practicas_fp" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."practicas_fp_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tutor_centro" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" "text",
    "email" "text",
    "telefono" "text"
);


ALTER TABLE "public"."tutor_centro" OWNER TO "postgres";


ALTER TABLE "public"."tutor_centro" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tutor_centro_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tutores" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" "text",
    "nif" "text" NOT NULL,
    "email" "text",
    "telefono" "text",
    "cif_empresa" "text" NOT NULL,
    "oferta" bigint
);


ALTER TABLE "public"."tutores" OWNER TO "postgres";


ALTER TABLE "public"."tutores" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tutores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."usuarios" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text",
    "password" character varying,
    "rol" "text"
);


ALTER TABLE "public"."usuarios" OWNER TO "postgres";


ALTER TABLE "public"."usuarios" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."usuarios_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."vw_empresas_ofertas" WITH ("security_invoker"='on') AS
 SELECT "e"."CIF",
    "e"."nombre",
    "e"."telefono",
    "e"."direccion",
    "e"."localidad",
    "e"."codigo_postal",
    "e"."email_empresa",
    "e"."responsable_legal",
    "e"."nif_responsable_legal",
    "e"."horario",
    "e"."pagina_web",
    "e"."nombre_rellena",
    "cf"."key" AS "ciclo_formativo",
    (("cf"."value" ->> 'alumnos'::"text"))::integer AS "alumnos_pedidos",
    (("cf"."value" ->> 'disponibles'::"text"))::integer AS "cupos_disponibles",
    ( SELECT "string_agg"("concat"(("pitem"."value" ->> 'area'::"text"), ' — ', ("pitem"."value" ->> 'proyecto'::"text")), ' | '::"text") AS "string_agg"
           FROM ("jsonb_each"("o"."puestos") "px"("key", "value")
             JOIN LATERAL "jsonb_array_elements"("px"."value") "pitem"("value") ON (true))
          WHERE ("px"."key" = "cf"."key")) AS "areas_puestos",
    "o"."requisitos",
    "o"."contrato",
    "o"."vehiculo",
    "o"."cupo_alumnos" AS "cupo_alumnos_totales_oferta",
    "t"."nombre" AS "tutor_nombre",
    "t"."email" AS "tutor_email",
    "t"."telefono" AS "tutor_telefono"
   FROM ((("public"."empresas" "e"
     JOIN "public"."oferta_fp" "o" ON ((("o"."empresa")::"text" = ("e"."CIF")::"text")))
     LEFT JOIN "public"."tutores" "t" ON (("t"."id" = "o"."tutor")))
     LEFT JOIN LATERAL "jsonb_each"("o"."ciclos_formativos") "cf"("key", "value") ON (true))
  ORDER BY "e"."nombre", "o"."id", "cf"."key";


ALTER VIEW "public"."vw_empresas_ofertas" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_feedback_detalle_alumnos" WITH ("security_invoker"='on') AS
 SELECT "e"."nombre" AS "empresa",
    ((("a"."nombre")::"text" || ' '::"text") || ("a"."apellido")::"text") AS "alumno",
    "a"."dni" AS "alumno_dni",
    "p"."id" AS "practica_id",
    "p"."created_at" AS "fecha_inicio_practica",
        CASE
            WHEN ("fr"."id" IS NOT NULL) THEN 'Respondido'::"text"
            ELSE 'Pendiente'::"text"
        END AS "estado",
    "fr"."created_at" AS "fecha_respuesta"
   FROM ((("public"."practicas_fp" "p"
     JOIN "public"."empresas" "e" ON ((("p"."empresa")::"text" = ("e"."CIF")::"text")))
     JOIN "public"."alumnos" "a" ON (("p"."alumno" = "a"."dni")))
     LEFT JOIN "public"."feedback_respuestas" "fr" ON (("p"."id" = "fr"."practica_id")))
  ORDER BY "e"."nombre", "p"."created_at" DESC;


ALTER VIEW "public"."vw_feedback_detalle_alumnos" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_feedback_resumen_empresas" WITH ("security_invoker"='on') AS
 SELECT "e"."nombre" AS "empresa",
    "e"."CIF",
    "count"("p"."id") AS "total_practicas",
    "count"("fr"."id") AS "total_respuestas",
        CASE
            WHEN ("count"("p"."id") > 0) THEN "round"(((("count"("fr"."id"))::numeric / ("count"("p"."id"))::numeric) * (100)::numeric), 2)
            ELSE (0)::numeric
        END AS "porcentaje_completado",
    "min"("fr"."created_at") AS "fecha_primer_feedback",
    "max"("fr"."created_at") AS "fecha_ultimo_feedback",
    "count"(
        CASE
            WHEN ("fr"."created_at" > (CURRENT_DATE - '30 days'::interval)) THEN 1
            ELSE NULL::integer
        END) AS "respuestas_ultimo_mes"
   FROM ((("public"."empresas" "e"
     JOIN "public"."practicas_fp" "p" ON ((("e"."CIF")::"text" = ("p"."empresa")::"text")))
     LEFT JOIN "public"."alumnos" "a" ON (("p"."alumno" = "a"."dni")))
     LEFT JOIN "public"."feedback_respuestas" "fr" ON (("p"."id" = "fr"."practica_id")))
  GROUP BY "e"."nombre", "e"."CIF"
  ORDER BY
        CASE
            WHEN ("count"("p"."id") > 0) THEN "round"(((("count"("fr"."id"))::numeric / ("count"("p"."id"))::numeric) * (100)::numeric), 2)
            ELSE (0)::numeric
        END DESC;


ALTER VIEW "public"."vw_feedback_resumen_empresas" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."vw_feedback_stats" WITH ("security_invoker"='on') AS
 WITH "base_data" AS (
         SELECT "e"."CIF" AS "empresa_cif",
            "e"."nombre" AS "empresa_nombre",
            "a"."id" AS "alumno_id",
            TRIM(BOTH FROM "concat"("a"."nombre", ' ', "a"."apellido")) AS "alumno_nombre",
            "p"."id" AS "practica_id",
            "p"."created_at" AS "fecha_inicio_practica",
            "fr"."id" AS "respuesta_id",
            "fr"."created_at" AS "fecha_respuesta",
                CASE
                    WHEN ("fr"."id" IS NOT NULL) THEN 1
                    ELSE 0
                END AS "respondido"
           FROM ((("public"."empresas" "e"
             JOIN "public"."practicas_fp" "p" ON ((("e"."CIF")::"text" = ("p"."empresa")::"text")))
             JOIN "public"."alumnos" "a" ON (("p"."alumno" = "a"."dni")))
             LEFT JOIN "public"."feedback_respuestas" "fr" ON (("p"."id" = "fr"."practica_id")))
        )
 SELECT "empresa_nombre",
    "empresa_cif",
    "count"("practica_id") AS "total_alumnos_asignados",
    "sum"("respondido") AS "total_respuestas_recibidas",
    "round"(((("sum"("respondido"))::numeric / (NULLIF("count"("practica_id"), 0))::numeric) * (100)::numeric), 2) AS "porcentaje_completado",
    "min"("fecha_inicio_practica") AS "primera_practica",
    "max"("fecha_respuesta") AS "ultima_respuesta_recibida",
    "count"(
        CASE
            WHEN ("date_trunc"('month'::"text", "fecha_respuesta") = "date_trunc"('month'::"text", (CURRENT_DATE)::timestamp with time zone)) THEN 1
            ELSE NULL::integer
        END) AS "respuestas_mes_actual"
   FROM "base_data"
  GROUP BY "empresa_nombre", "empresa_cif"
  ORDER BY ("round"(((("sum"("respondido"))::numeric / (NULLIF("count"("practica_id"), 0))::numeric) * (100)::numeric), 2)) DESC;


ALTER VIEW "public"."vw_feedback_stats" OWNER TO "postgres";


ALTER TABLE ONLY "public"."alumno_estados"
    ADD CONSTRAINT "alumno_estados_pkey" PRIMARY KEY ("alumno");



ALTER TABLE ONLY "public"."alumnos"
    ADD CONSTRAINT "alumnos_dni_unique" UNIQUE ("dni");



ALTER TABLE ONLY "public"."alumnos"
    ADD CONSTRAINT "alumnos_pkey" PRIMARY KEY ("dni");



ALTER TABLE ONLY "public"."contacto_alumnos"
    ADD CONSTRAINT "contacto_alumnos_pkey" PRIMARY KEY ("email_alumno");



ALTER TABLE ONLY "public"."contacto_empresas"
    ADD CONSTRAINT "contacto_empresas_pkey" PRIMARY KEY ("email_empresa");



ALTER TABLE ONLY "public"."empresa_estados"
    ADD CONSTRAINT "empresa_estados_pkey" PRIMARY KEY ("empresa");



ALTER TABLE ONLY "public"."empresas"
    ADD CONSTRAINT "empresas_pkey" PRIMARY KEY ("CIF");



ALTER TABLE ONLY "public"."error_logs"
    ADD CONSTRAINT "error_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."feedback_forms"
    ADD CONSTRAINT "feedback_forms_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."feedback_respuestas"
    ADD CONSTRAINT "feedback_respuestas_feedback_form_id_key" UNIQUE ("feedback_form_id");



ALTER TABLE ONLY "public"."feedback_respuestas"
    ADD CONSTRAINT "feedback_respuestas_pkey" PRIMARY KEY ("feedback_form_id", "practica_id");



ALTER TABLE ONLY "public"."feedback_respuestas"
    ADD CONSTRAINT "feedback_respuestas_practica_id_key" UNIQUE ("practica_id");



ALTER TABLE ONLY "public"."feedback_respuestas"
    ADD CONSTRAINT "feedback_respuestas_upsert_key" UNIQUE ("feedback_form_id", "practica_id");



ALTER TABLE ONLY "public"."form_answers"
    ADD CONSTRAINT "form_answers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."form_fields"
    ADD CONSTRAINT "form_fields_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."forms"
    ADD CONSTRAINT "forms_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."gestores"
    ADD CONSTRAINT "gestores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."localidades"
    ADD CONSTRAINT "localidades_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."oferta_fp"
    ADD CONSTRAINT "oferta_fp_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."practicas_fp"
    ADD CONSTRAINT "practica_alumno_oferta_unique" UNIQUE ("alumno", "oferta");



ALTER TABLE ONLY "public"."practica_estados"
    ADD CONSTRAINT "practica_estados_pkey" PRIMARY KEY ("practicaId");



ALTER TABLE ONLY "public"."practicas_canceladas"
    ADD CONSTRAINT "practicas_canceladas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."practicas_fp"
    ADD CONSTRAINT "practicas_fp_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tutor_centro"
    ADD CONSTRAINT "tutor_centro_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tutores"
    ADD CONSTRAINT "tutores_pkey" PRIMARY KEY ("nif");



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "usuarios_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."alumno_estados"
    ADD CONSTRAINT "alumno_estados_alumno_fkey" FOREIGN KEY ("alumno") REFERENCES "public"."alumnos"("dni") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."empresa_estados"
    ADD CONSTRAINT "empresa_estados_empresa_fkey" FOREIGN KEY ("empresa") REFERENCES "public"."empresas"("CIF");



ALTER TABLE ONLY "public"."feedback_forms"
    ADD CONSTRAINT "feedback_forms_practica_id_fkey" FOREIGN KEY ("practica_id") REFERENCES "public"."practicas_fp"("id");



ALTER TABLE ONLY "public"."feedback_respuestas"
    ADD CONSTRAINT "feedback_respuestas_feedback_form_id_fkey" FOREIGN KEY ("feedback_form_id") REFERENCES "public"."feedback_forms"("id");



ALTER TABLE ONLY "public"."feedback_respuestas"
    ADD CONSTRAINT "feedback_respuestas_practica_id_fkey" FOREIGN KEY ("practica_id") REFERENCES "public"."practicas_fp"("id");



ALTER TABLE ONLY "public"."form_answers"
    ADD CONSTRAINT "form_answers_empresa_fkey" FOREIGN KEY ("empresa") REFERENCES "public"."empresas"("CIF");



ALTER TABLE ONLY "public"."form_answers"
    ADD CONSTRAINT "form_answers_field_id_fkey" FOREIGN KEY ("field_id") REFERENCES "public"."form_fields"("id");



ALTER TABLE ONLY "public"."form_answers"
    ADD CONSTRAINT "form_answers_form_fkey" FOREIGN KEY ("form") REFERENCES "public"."forms"("id");



ALTER TABLE ONLY "public"."form_fields"
    ADD CONSTRAINT "form_fields_form_fkey" FOREIGN KEY ("form") REFERENCES "public"."forms"("id");



ALTER TABLE ONLY "public"."oferta_fp"
    ADD CONSTRAINT "oferta_fp_empresa_fkey" FOREIGN KEY ("empresa") REFERENCES "public"."empresas"("CIF");



ALTER TABLE ONLY "public"."practica_estados"
    ADD CONSTRAINT "practica_estados_practicaId_fkey" FOREIGN KEY ("practicaId") REFERENCES "public"."practicas_fp"("id");



ALTER TABLE ONLY "public"."practicas_fp"
    ADD CONSTRAINT "practicas_fp_alumno_fkey" FOREIGN KEY ("alumno") REFERENCES "public"."alumnos"("dni");



ALTER TABLE ONLY "public"."practicas_fp"
    ADD CONSTRAINT "practicas_fp_empresa_fkey" FOREIGN KEY ("empresa") REFERENCES "public"."empresas"("CIF");



ALTER TABLE ONLY "public"."practicas_fp"
    ADD CONSTRAINT "practicas_fp_oferta_fkey" FOREIGN KEY ("oferta") REFERENCES "public"."oferta_fp"("id");



ALTER TABLE ONLY "public"."tutores"
    ADD CONSTRAINT "tutores_CIF_empresa_fkey" FOREIGN KEY ("cif_empresa") REFERENCES "public"."empresas"("CIF");



ALTER TABLE ONLY "public"."tutores"
    ADD CONSTRAINT "tutores_oferta_fkey" FOREIGN KEY ("oferta") REFERENCES "public"."oferta_fp"("id");



ALTER TABLE "public"."alumno_estados" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."alumnos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."contacto_alumnos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."contacto_empresas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."empresa_estados" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."empresas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."error_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."feedback_forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."feedback_respuestas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."form_answers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."form_fields" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."gestores" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."localidades" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."oferta_fp" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."practica_estados" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."practicas_canceladas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."practicas_fp" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "read" ON "public"."alumno_estados" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."alumnos" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."contacto_alumnos" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."contacto_empresas" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."empresa_estados" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."empresas" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."error_logs" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."feedback_forms" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."feedback_respuestas" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."form_answers" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."form_fields" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."forms" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."gestores" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."localidades" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."oferta_fp" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."practica_estados" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."practicas_canceladas" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."practicas_fp" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."tutor_centro" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."tutores" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."usuarios" USING (true) WITH CHECK (true);



ALTER TABLE "public"."tutor_centro" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tutores" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."usuarios" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."feedback_respuestas";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."exec_sql"("sql" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."exec_sql"("sql" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."exec_sql"("sql" "text") TO "service_role";


















GRANT ALL ON TABLE "public"."alumno_estados" TO "anon";
GRANT ALL ON TABLE "public"."alumno_estados" TO "authenticated";
GRANT ALL ON TABLE "public"."alumno_estados" TO "service_role";



GRANT ALL ON SEQUENCE "public"."alumno_estados_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."alumno_estados_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."alumno_estados_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."alumnos" TO "anon";
GRANT ALL ON TABLE "public"."alumnos" TO "authenticated";
GRANT ALL ON TABLE "public"."alumnos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."alumnos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."alumnos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."alumnos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."contacto_alumnos" TO "anon";
GRANT ALL ON TABLE "public"."contacto_alumnos" TO "authenticated";
GRANT ALL ON TABLE "public"."contacto_alumnos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."contacto_alumnos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."contacto_alumnos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."contacto_alumnos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."contacto_empresas" TO "anon";
GRANT ALL ON TABLE "public"."contacto_empresas" TO "authenticated";
GRANT ALL ON TABLE "public"."contacto_empresas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."contacto_empresas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."contacto_empresas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."contacto_empresas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."empresa_estados" TO "anon";
GRANT ALL ON TABLE "public"."empresa_estados" TO "authenticated";
GRANT ALL ON TABLE "public"."empresa_estados" TO "service_role";



GRANT ALL ON SEQUENCE "public"."empresa_estados_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."empresa_estados_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."empresa_estados_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."oferta_fp" TO "anon";
GRANT ALL ON TABLE "public"."oferta_fp" TO "authenticated";
GRANT ALL ON TABLE "public"."oferta_fp" TO "service_role";



GRANT ALL ON SEQUENCE "public"."empresa_practica_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."empresa_practica_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."empresa_practica_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."empresas" TO "anon";
GRANT ALL ON TABLE "public"."empresas" TO "authenticated";
GRANT ALL ON TABLE "public"."empresas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."empresas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."empresas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."empresas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."error_logs" TO "anon";
GRANT ALL ON TABLE "public"."error_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."error_logs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."error_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."error_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."error_logs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."feedback_forms" TO "anon";
GRANT ALL ON TABLE "public"."feedback_forms" TO "authenticated";
GRANT ALL ON TABLE "public"."feedback_forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."feedback_forms_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."feedback_forms_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."feedback_forms_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."feedback_respuestas" TO "anon";
GRANT ALL ON TABLE "public"."feedback_respuestas" TO "authenticated";
GRANT ALL ON TABLE "public"."feedback_respuestas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."feedback_respuestas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."feedback_respuestas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."feedback_respuestas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."form_answers" TO "anon";
GRANT ALL ON TABLE "public"."form_answers" TO "authenticated";
GRANT ALL ON TABLE "public"."form_answers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."form_answers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."form_answers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."form_answers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."form_fields" TO "anon";
GRANT ALL ON TABLE "public"."form_fields" TO "authenticated";
GRANT ALL ON TABLE "public"."form_fields" TO "service_role";



GRANT ALL ON SEQUENCE "public"."form_fields_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."form_fields_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."form_fields_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."forms" TO "anon";
GRANT ALL ON TABLE "public"."forms" TO "authenticated";
GRANT ALL ON TABLE "public"."forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."forms_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."forms_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."forms_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."gestores" TO "anon";
GRANT ALL ON TABLE "public"."gestores" TO "authenticated";
GRANT ALL ON TABLE "public"."gestores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."gestores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."gestores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."gestores_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."localidades" TO "anon";
GRANT ALL ON TABLE "public"."localidades" TO "authenticated";
GRANT ALL ON TABLE "public"."localidades" TO "service_role";



GRANT ALL ON TABLE "public"."practica_estados" TO "anon";
GRANT ALL ON TABLE "public"."practica_estados" TO "authenticated";
GRANT ALL ON TABLE "public"."practica_estados" TO "service_role";



GRANT ALL ON SEQUENCE "public"."practica_estados_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."practica_estados_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."practica_estados_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."practicas_canceladas" TO "anon";
GRANT ALL ON TABLE "public"."practicas_canceladas" TO "authenticated";
GRANT ALL ON TABLE "public"."practicas_canceladas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."practicas_canceladas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."practicas_canceladas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."practicas_canceladas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."practicas_fp" TO "anon";
GRANT ALL ON TABLE "public"."practicas_fp" TO "authenticated";
GRANT ALL ON TABLE "public"."practicas_fp" TO "service_role";



GRANT ALL ON SEQUENCE "public"."practicas_fp_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."practicas_fp_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."practicas_fp_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tutor_centro" TO "anon";
GRANT ALL ON TABLE "public"."tutor_centro" TO "authenticated";
GRANT ALL ON TABLE "public"."tutor_centro" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tutor_centro_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tutor_centro_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tutor_centro_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tutores" TO "anon";
GRANT ALL ON TABLE "public"."tutores" TO "authenticated";
GRANT ALL ON TABLE "public"."tutores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tutores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tutores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tutores_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."usuarios" TO "anon";
GRANT ALL ON TABLE "public"."usuarios" TO "authenticated";
GRANT ALL ON TABLE "public"."usuarios" TO "service_role";



GRANT ALL ON SEQUENCE "public"."usuarios_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."usuarios_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."usuarios_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."vw_empresas_ofertas" TO "anon";
GRANT ALL ON TABLE "public"."vw_empresas_ofertas" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_empresas_ofertas" TO "service_role";



GRANT ALL ON TABLE "public"."vw_feedback_detalle_alumnos" TO "anon";
GRANT ALL ON TABLE "public"."vw_feedback_detalle_alumnos" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_feedback_detalle_alumnos" TO "service_role";



GRANT ALL ON TABLE "public"."vw_feedback_resumen_empresas" TO "anon";
GRANT ALL ON TABLE "public"."vw_feedback_resumen_empresas" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_feedback_resumen_empresas" TO "service_role";



GRANT ALL ON TABLE "public"."vw_feedback_stats" TO "anon";
GRANT ALL ON TABLE "public"."vw_feedback_stats" TO "authenticated";
GRANT ALL ON TABLE "public"."vw_feedback_stats" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































