


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."exec_sql"("sql" "text") RETURNS SETOF "jsonb"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN QUERY EXECUTE format('SELECT to_jsonb(t) FROM (%s) t', sql);
END;
$$;


ALTER FUNCTION "public"."exec_sql"("sql" "text") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."alumno_estados" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email_enviado" "date",
    "match_fp" "date",
    "fp_enprogreso" "date",
    "fp_finalizada" "date",
    "alumno" character varying NOT NULL,
    "form_completo" "date",
    "documentacion_completa" "date",
    "evaluacion_enviada" "date",
    "evaluacion_completa" "date",
    "fp_asignada" "date"
);


ALTER TABLE "public"."alumno_estados" OWNER TO "postgres";


ALTER TABLE "public"."alumno_estados" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."alumno_estados_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."alumnos" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "NIA" character varying,
    "nombre" character varying,
    "apellido" character varying,
    "apellido 2" character varying,
    "telefono" character varying,
    "provincia" character varying,
    "localidad" character varying,
    "codigo_postal" character varying,
    "direccion" character varying,
    "email_alumno" character varying,
    "sexo" character varying,
    "preferencias_fp" "jsonb",
    "vehiculo" "text",
    "ciclo_formativo" "jsonb",
    "estado" character varying,
    "motivo" character varying,
    "dni" "text" NOT NULL,
    "requisitos" character varying,
    "tipoPractica" "text"
);


ALTER TABLE "public"."alumnos" OWNER TO "postgres";


ALTER TABLE "public"."alumnos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."alumnos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."contacto_alumnos" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email_alumno" character varying NOT NULL,
    "email_enviado" "date"
);


ALTER TABLE "public"."contacto_alumnos" OWNER TO "postgres";


ALTER TABLE "public"."contacto_alumnos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."contacto_alumnos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."contacto_empresas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email_empresa" character varying NOT NULL,
    "email_enviado" "date"
);


ALTER TABLE "public"."contacto_empresas" OWNER TO "postgres";


ALTER TABLE "public"."contacto_empresas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."contacto_empresas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."empresa_estados" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email_enviado" "date",
    "form_completo" "date",
    "contrato_firmado" "date",
    "fp_asignada" "date",
    "fp_enprogreso" "date",
    "fp_finalizada" "date",
    "empresa" character varying NOT NULL,
    "documentacion_completa" "date",
    "match_fp" "date",
    "evaluacion_enviada" "date",
    "evaluacion_completa" "date"
);


ALTER TABLE "public"."empresa_estados" OWNER TO "postgres";


ALTER TABLE "public"."empresa_estados" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."empresa_estados_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."oferta_fp" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "empresa" character varying NOT NULL,
    "ciclos_formativos" "jsonb",
    "puestos" "jsonb",
    "requisitos" character varying,
    "contrato" character varying,
    "vehiculo" character varying,
    "estado" character varying,
    "motivo" character varying,
    "direccion_empresa" character varying,
    "localidad_empresa" character varying,
    "cp_empresa" character varying,
    "nombre_rellena_form" character varying,
    "cupo_alumnos" real,
    "tutor" bigint
);


ALTER TABLE "public"."oferta_fp" OWNER TO "postgres";


ALTER TABLE "public"."oferta_fp" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."empresa_practica_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."empresas" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "CIF" character varying NOT NULL,
    "nombre" "text",
    "direccion" "text",
    "provincia" "text",
    "localidad" "text",
    "codigo_postal" character varying,
    "telefono" "text",
    "fax" "text",
    "tipo_empresa" "text",
    "email_empresa" "text",
    "responsable_legal" "text",
    "nif_responsable_legal" "text",
    "horario" "text",
    "pagina_web" "text",
    "nombre_rellena" "text"
);


ALTER TABLE "public"."empresas" OWNER TO "postgres";


ALTER TABLE "public"."empresas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."empresas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."form_answers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "form" bigint,
    "field_id" bigint,
    "empresa" character varying,
    "value" "text",
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."form_answers" OWNER TO "postgres";


ALTER TABLE "public"."form_answers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."form_answers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."form_fields" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "form" bigint,
    "label" "text",
    "type" "text",
    "options" "jsonb",
    "required" boolean,
    "order_index" bigint,
    "category" "text",
    "columnName" "text"
);


ALTER TABLE "public"."form_fields" OWNER TO "postgres";


ALTER TABLE "public"."form_fields" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."form_fields_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."forms" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" character varying,
    "tipo" character varying,
    "descripcion" "text"
);


ALTER TABLE "public"."forms" OWNER TO "postgres";


ALTER TABLE "public"."forms" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."forms_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."practica_estados" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "practicaId" bigint,
    "documentacion_pedida" "date",
    "documentacion_firmada" "date",
    "en_progreso" "date",
    "cancelada" "date",
    "finalizada" "date"
);


ALTER TABLE "public"."practica_estados" OWNER TO "postgres";


ALTER TABLE "public"."practica_estados" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."practica_estados_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."practicas_fp" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "empresa" character varying,
    "oferta" bigint,
    "alumno" "text",
    "ciclo_formativo" character varying,
    "area" character varying,
    "proyecto" character varying
);


ALTER TABLE "public"."practicas_fp" OWNER TO "postgres";


ALTER TABLE "public"."practicas_fp" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."practicas_fp_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tutores" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nombre" "text",
    "nif" "text" NOT NULL,
    "email" "text",
    "telefono" "text",
    "cif_empresa" "text" NOT NULL,
    "oferta" bigint
);


ALTER TABLE "public"."tutores" OWNER TO "postgres";


ALTER TABLE "public"."tutores" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tutores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."usuarios" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" "text",
    "password" character varying
);


ALTER TABLE "public"."usuarios" OWNER TO "postgres";


ALTER TABLE "public"."usuarios" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."usuarios_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."alumno_estados"
    ADD CONSTRAINT "alumno_estados_pkey" PRIMARY KEY ("alumno");



ALTER TABLE ONLY "public"."alumnos"
    ADD CONSTRAINT "alumnos_dni_unique" UNIQUE ("dni");



ALTER TABLE ONLY "public"."alumnos"
    ADD CONSTRAINT "alumnos_pkey" PRIMARY KEY ("dni");



ALTER TABLE ONLY "public"."contacto_alumnos"
    ADD CONSTRAINT "contacto_alumnos_pkey" PRIMARY KEY ("email_alumno");



ALTER TABLE ONLY "public"."contacto_empresas"
    ADD CONSTRAINT "contacto_empresas_pkey" PRIMARY KEY ("email_empresa");



ALTER TABLE ONLY "public"."empresa_estados"
    ADD CONSTRAINT "empresa_estados_pkey" PRIMARY KEY ("empresa");



ALTER TABLE ONLY "public"."empresas"
    ADD CONSTRAINT "empresas_pkey" PRIMARY KEY ("CIF");



ALTER TABLE ONLY "public"."form_answers"
    ADD CONSTRAINT "form_answers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."form_fields"
    ADD CONSTRAINT "form_fields_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."forms"
    ADD CONSTRAINT "forms_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."oferta_fp"
    ADD CONSTRAINT "oferta_fp_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."practicas_fp"
    ADD CONSTRAINT "practica_alumno_oferta_unique" UNIQUE ("alumno", "oferta");



ALTER TABLE ONLY "public"."practica_estados"
    ADD CONSTRAINT "practica_estados_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."practicas_fp"
    ADD CONSTRAINT "practicas_fp_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tutores"
    ADD CONSTRAINT "tutores_pkey" PRIMARY KEY ("nif");



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "usuarios_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."alumno_estados"
    ADD CONSTRAINT "alumno_estados_alumno_fkey" FOREIGN KEY ("alumno") REFERENCES "public"."alumnos"("dni") ON UPDATE CASCADE ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."empresa_estados"
    ADD CONSTRAINT "empresa_estados_empresa_fkey" FOREIGN KEY ("empresa") REFERENCES "public"."empresas"("CIF");



ALTER TABLE ONLY "public"."form_answers"
    ADD CONSTRAINT "form_answers_empresa_fkey" FOREIGN KEY ("empresa") REFERENCES "public"."empresas"("CIF");



ALTER TABLE ONLY "public"."form_answers"
    ADD CONSTRAINT "form_answers_field_id_fkey" FOREIGN KEY ("field_id") REFERENCES "public"."form_fields"("id");



ALTER TABLE ONLY "public"."form_answers"
    ADD CONSTRAINT "form_answers_form_fkey" FOREIGN KEY ("form") REFERENCES "public"."forms"("id");



ALTER TABLE ONLY "public"."form_fields"
    ADD CONSTRAINT "form_fields_form_fkey" FOREIGN KEY ("form") REFERENCES "public"."forms"("id");



ALTER TABLE ONLY "public"."oferta_fp"
    ADD CONSTRAINT "oferta_fp_empresa_fkey" FOREIGN KEY ("empresa") REFERENCES "public"."empresas"("CIF");



ALTER TABLE ONLY "public"."practica_estados"
    ADD CONSTRAINT "practica_estados_practicaId_fkey" FOREIGN KEY ("practicaId") REFERENCES "public"."practicas_fp"("id");



ALTER TABLE ONLY "public"."practicas_fp"
    ADD CONSTRAINT "practicas_fp_alumno_fkey" FOREIGN KEY ("alumno") REFERENCES "public"."alumnos"("dni");



ALTER TABLE ONLY "public"."practicas_fp"
    ADD CONSTRAINT "practicas_fp_empresa_fkey" FOREIGN KEY ("empresa") REFERENCES "public"."empresas"("CIF");



ALTER TABLE ONLY "public"."practicas_fp"
    ADD CONSTRAINT "practicas_fp_oferta_fkey" FOREIGN KEY ("oferta") REFERENCES "public"."oferta_fp"("id");



ALTER TABLE ONLY "public"."tutores"
    ADD CONSTRAINT "tutores_CIF_empresa_fkey" FOREIGN KEY ("cif_empresa") REFERENCES "public"."empresas"("CIF");



ALTER TABLE ONLY "public"."tutores"
    ADD CONSTRAINT "tutores_oferta_fkey" FOREIGN KEY ("oferta") REFERENCES "public"."oferta_fp"("id");



ALTER TABLE "public"."alumno_estados" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."alumnos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."contacto_alumnos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."contacto_empresas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."empresa_estados" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."empresas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."form_answers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."form_fields" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."forms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."oferta_fp" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."practica_estados" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."practicas_fp" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "read" ON "public"."alumno_estados" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."alumnos" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."contacto_alumnos" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."contacto_empresas" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."empresa_estados" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."empresas" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."form_answers" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."form_fields" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."forms" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."oferta_fp" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."practica_estados" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."practicas_fp" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."tutores" USING (true) WITH CHECK (true);



CREATE POLICY "read" ON "public"."usuarios" USING (true) WITH CHECK (true);



ALTER TABLE "public"."tutores" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."usuarios" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."exec_sql"("sql" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."exec_sql"("sql" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."exec_sql"("sql" "text") TO "service_role";


















GRANT ALL ON TABLE "public"."alumno_estados" TO "anon";
GRANT ALL ON TABLE "public"."alumno_estados" TO "authenticated";
GRANT ALL ON TABLE "public"."alumno_estados" TO "service_role";



GRANT ALL ON SEQUENCE "public"."alumno_estados_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."alumno_estados_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."alumno_estados_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."alumnos" TO "anon";
GRANT ALL ON TABLE "public"."alumnos" TO "authenticated";
GRANT ALL ON TABLE "public"."alumnos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."alumnos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."alumnos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."alumnos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."contacto_alumnos" TO "anon";
GRANT ALL ON TABLE "public"."contacto_alumnos" TO "authenticated";
GRANT ALL ON TABLE "public"."contacto_alumnos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."contacto_alumnos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."contacto_alumnos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."contacto_alumnos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."contacto_empresas" TO "anon";
GRANT ALL ON TABLE "public"."contacto_empresas" TO "authenticated";
GRANT ALL ON TABLE "public"."contacto_empresas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."contacto_empresas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."contacto_empresas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."contacto_empresas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."empresa_estados" TO "anon";
GRANT ALL ON TABLE "public"."empresa_estados" TO "authenticated";
GRANT ALL ON TABLE "public"."empresa_estados" TO "service_role";



GRANT ALL ON SEQUENCE "public"."empresa_estados_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."empresa_estados_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."empresa_estados_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."oferta_fp" TO "anon";
GRANT ALL ON TABLE "public"."oferta_fp" TO "authenticated";
GRANT ALL ON TABLE "public"."oferta_fp" TO "service_role";



GRANT ALL ON SEQUENCE "public"."empresa_practica_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."empresa_practica_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."empresa_practica_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."empresas" TO "anon";
GRANT ALL ON TABLE "public"."empresas" TO "authenticated";
GRANT ALL ON TABLE "public"."empresas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."empresas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."empresas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."empresas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."form_answers" TO "anon";
GRANT ALL ON TABLE "public"."form_answers" TO "authenticated";
GRANT ALL ON TABLE "public"."form_answers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."form_answers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."form_answers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."form_answers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."form_fields" TO "anon";
GRANT ALL ON TABLE "public"."form_fields" TO "authenticated";
GRANT ALL ON TABLE "public"."form_fields" TO "service_role";



GRANT ALL ON SEQUENCE "public"."form_fields_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."form_fields_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."form_fields_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."forms" TO "anon";
GRANT ALL ON TABLE "public"."forms" TO "authenticated";
GRANT ALL ON TABLE "public"."forms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."forms_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."forms_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."forms_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."practica_estados" TO "anon";
GRANT ALL ON TABLE "public"."practica_estados" TO "authenticated";
GRANT ALL ON TABLE "public"."practica_estados" TO "service_role";



GRANT ALL ON SEQUENCE "public"."practica_estados_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."practica_estados_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."practica_estados_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."practicas_fp" TO "anon";
GRANT ALL ON TABLE "public"."practicas_fp" TO "authenticated";
GRANT ALL ON TABLE "public"."practicas_fp" TO "service_role";



GRANT ALL ON SEQUENCE "public"."practicas_fp_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."practicas_fp_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."practicas_fp_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tutores" TO "anon";
GRANT ALL ON TABLE "public"."tutores" TO "authenticated";
GRANT ALL ON TABLE "public"."tutores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tutores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tutores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tutores_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."usuarios" TO "anon";
GRANT ALL ON TABLE "public"."usuarios" TO "authenticated";
GRANT ALL ON TABLE "public"."usuarios" TO "service_role";



GRANT ALL ON SEQUENCE "public"."usuarios_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."usuarios_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."usuarios_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































